[project]
name = "core"
version = "0.1.0"
description = "Currency Converter API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "pydantic-settings",
    "python-dotenv",
    "requests",
    "redis>=6.1.0",
]
